### PR TITLE
Support PyTango 7 and 8

### PR DESCRIPTION
**Pull request by vxgmichel**
Needed for sardana: [see ticket #487](https://sourceforge.net/p/sardana/tickets/487/)

### CODE REVIEW

**Comment by picca** [comment]
what about the scripts ?
PyTango < 9.2.0 -> provide /usr/bin/itango[3]
itango -> provides /usr/bin/itango[3] + itango-qt

**Comment by reszelaz** [comment]
The changes looks ok to me. I have also tested it with PyTango 8.1.1 and it works.

@picca your concern is about the itango script that would override the one installed by PyTango < 9.2.0, right?

@vxgmichel will you wait until we perform the extensive Sardana tests, hence we should use this branch? Or you plan to merge it first?

**Comment by picca** [comment]
Yes but from the point of view of Debian ;) we will upload tango 9.2.0 and itango.
 we will not support pytango < 9.2.0 + itango.
We have only one combination installed  on the system.

**Comment by vxgmichel** [comment]
@reszelaz I'm planning to add IPython 5 + qtconsole support then bump the version to 0.1.4. Is it OK with you?

**Comment by reszelaz** [comment]
I just found one problem. I see in the itango requirements that it need IPython>=1.0 while Sardana still supports IPython 0.10. We can not drop support to ipython 0.10 yet.
Having this in mind, I think that we can not set the requirement to itango >= 0.1.4 in Sardana.
I'm afraid that we will need to leave Sardana without the correct requirement for users willing to upgrade to PyTango >= 9.2.

**Comment by vxgmichel** [comment]
@reszelaz IPython 0.10? That's a tough one... I guess I could lower the IPython requirements since PyTango < 9 supports it and I don't see why anyone would install ipython 0.10 along with pytango 9.

**Comment by reszelaz** [comment]
If you can lower the requirement that would solve the problem.

> I'm planning to add IPython 5 + qtconsole support then bump the version to 0.1.4. Is it OK with you?

I assume this would not add extra requirements?

**Comment by vxgmichel** [comment]
> If you can lower the requirement that would solve the problem.

Ok, let's do that then

> I assume this would not add extra requirements?

No, no extra requirements

**Pull request merged**
